import { Inter } from "next/font/google";
import "./globals.css";
import DrawerAppBar from "@/clientComponent/header/header";
import MouseHover from "@/clientComponent/mouseHover/mousehoverComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MouseHover />
        <DrawerAppBar />
        {children}
      </body>
    </html>
  );
}
